services:
  - type: web
    name: kitchen-line-bot
    env: docker
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/linebot-0.0.1-SNAPSHOT.jar
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_TOKEN
        sync: false
    autoDeploy: true
